# Generated by Django 4.1.7 on 2023-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
        ("accounts", "0002_alter_user_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_stories",
            field=models.ManyToManyField(
                related_name="saved_by_users", to="story.story"
            ),
        ),
    ]
