# Generated by Django 3.2.18 on 2023-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_alter_tag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
