# Generated by Django 3.2.18 on 2023-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="chapters",
            field=models.ManyToManyField(blank=True, null=True, to="story.Story"),
        ),
    ]
